# Config for Dad : https://github.com/pior/dad

up:
  - python: 3.6.4
  - pipfile
  - docker-compose  # Not working yet
  - custom:
      name: Install SASSC
      met?: which sassc
      meet: brew install sassc

commands:
  test:
    run: python manage.py test
  lint:
    run: flake8

  server:
    run: python manage.py runserver

  db-migrate:
    run: python manage.py migrate
  db-seed:
    run: python manage.py loaddata fixtures/00{1,2,3,4}_*.json

  css:
    run: sassc mtlpy/static/css/style.scss mtlpy/static/css/style.css --style expanded
