# Config for Dad : https://github.com/pior/dad

up:
  - python: 3.6.4
  - pipfile
  - homebrew: [sassc]
  - custom:
      name: Create the .env file
      met?: test -e .env
      meet: cp .env.example .env && echo "✅  The file .env has been copied from .env.example"

commands:
  test:
    desc: Run the tests with Django runner
    run: python manage.py test
  lint:
    run: flake8

  server:
    run: python manage.py runserver

  db-migrate:
    run: python manage.py migrate
  db-seed:
    run: python manage.py loaddata fixtures/00{1,2,3,4}_*.json

  css:
    run: sassc mtlpy/static/css/style.scss mtlpy/static/css/style.css --style expanded
