version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      MYSQL_DATABASE: mtlpy
    ports:
      - "3307:3306"
    expose:
      - "3307"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
