version: "3.7"

services:
  db:
    image: postgres:9.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: mtlpy
      POSTGRES_USER: mtlpy
      POSTGRES_PASSWORD: mtlpy
    ports:
      - "5432:5432"
