version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
      MYSQL_DATABASE: mtlpy
    ports:
      - "3307:3306"
    expose:
      - "3307"
    command: --default-authentication-plugin=mysql_native_password
