version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
      - image: circleci/mysql:5.7.20-ram

    steps:
      - checkout

      - restore_cache:
          key: build-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run: |
          python3 -m venv /tmp/venv
          . /tmp/venv/bin/activate

          pip install --upgrade setuptools
          pip install pipenv
          pipenv install --dev --system

      - save_cache:
          key: build-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "/tmp/venv"

      - run:
          command: |
            . /tmp/venv/bin/activate

            flake8

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          command: |
            . /tmp/venv/bin/activate

            python manage.py test
          environment:
            ENV: TEST
            DATABASE_URL: mysql://root:@localhost:3306/circle_test
            SECRET_KEY: TEST_SECRET_KEY
            AWS_ACCESS_KEY_ID: TEST_AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: TEST_AWS_SECRET_ACCESS_KEY
            AWS_STORAGE_BUCKET_NAME: TEST_AWS_STORAGE_BUCKET_NAME
            SLACKIN_TOKEN: TEST_SLACKIN_TOKEN
