version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    steps:
      - checkout

      - restore_cache:
          key: venv-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

      - run: |
          virtualenv venv
          . venv/bin/activate
          pip install --upgrade setuptools
          pip install pipenv
          pipenv install --dev --system

      - save_cache:
          key: venv-{{ arch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"

      - run:
          command: |
            . venv/bin/activate
            flake8
